# This Makefile is for the My::Module extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.70 (Revision: 77000) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#

#   MakeMaker Parameters:

#     MIN_PERL_VERSION => q[5.006]
#     PREREQ_PM => { Carp=>q[0], Class::Method::Modifiers=>q[1.10], Exporter=>q[0], Role::Tiny=>q[2.003000], Scalar::Util=>q[1.00], Sub::Defer=>q[2.006006], Sub::Quote=>q[2.006006], Test::More=>q[0.94] }
#     TEST_REQUIRES => { Test::More=>q[0.94] }

# --- MakeMaker post_initialize section:


