name: check

on: [push]

jobs:
  META.json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - id: get-prereqs
        uses: ./
        working-directory: test/corpus
      - run: echo $PREREQS
        env:
          PREREQS: ${{ steps.get-prereqs.prereqs }}
