name: check

on: [push]

jobs:
  META-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-prereqs
        uses: ./
        with:
          sources: test/corpus/META.json
      - run: echo $PREREQS
        env:
          PREREQS: ${{ steps.get-prereqs.prereqs }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
